# Generated by Django 6.0.3 on 2026-03-27 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.CharField(default='🏆', max_length=10, verbose_name='Иконка (эмодзи/символ)')),
                ('condition_type', models.CharField(choices=[('lessons_completed', 'Пройдено уроков'), ('courses_completed', 'Пройдено курсов'), ('control_completed', 'Пройдено контрольных'), ('xp_earned', 'Заработано XP'), ('level_reached', 'Достигнут уровень'), ('first_login', 'Первый вход'), ('chat_messages', 'Сообщений в чате')], max_length=30, verbose_name='Тип условия')),
                ('condition_value', models.IntegerField(verbose_name='Значение условия')),
                ('xp_reward', models.IntegerField(default=0, verbose_name='Награда XP')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрытое достижение')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок отображения')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Достижение',
                'verbose_name_plural': 'Достижения',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название курса')),
                ('description', models.TextField(verbose_name='Описание курса')),
                ('color', models.CharField(default='#0ea5e9', max_length=7, verbose_name='Цвет курса')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourseChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=1000, verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удалено')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages', to='lessons.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Сообщение чата',
                'verbose_name_plural': 'Сообщения чата',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название урока')),
                ('content', models.TextField(verbose_name='Текст урока (теория)')),
                ('code_task', models.TextField(verbose_name='Задание для кода')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('is_control', models.BooleanField(default=False, verbose_name='Контрольная работа')),
                ('xp_reward', models.IntegerField(default=50, verbose_name='Награда XP')),
                ('expected_output', models.TextField(blank=True, verbose_name='Ожидаемый вывод кода')),
                ('test_input', models.TextField(blank=True, verbose_name='Тестовые входные данные')),
                ('max_attempts', models.IntegerField(default=0, verbose_name='Максимум попыток')),
                ('require_input', models.BooleanField(default=True, verbose_name='Требовать input()')),
                ('require_variable', models.CharField(blank=True, help_text='Название переменной', max_length=50, verbose_name='Обязательная переменная')),
                ('forbidden_values', models.TextField(blank=True, help_text='Через запятую', verbose_name='Запрещённые значения')),
                ('check_ast', models.BooleanField(default=True, verbose_name='Включить проверку структуры')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xp', models.IntegerField(default=0, verbose_name='Опыт')),
                ('level', models.IntegerField(default=1, verbose_name='Уровень')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар')),
                ('bio', models.TextField(blank=True, default='', max_length=500, verbose_name='О себе')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль пользователя',
                'verbose_name_plural': 'Профили пользователей',
                'ordering': ['-xp', '-level'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='Получено')),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Полученное достижение',
                'verbose_name_plural': 'Полученные достижения',
                'ordering': ['-earned_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('code_solution', models.TextField(blank=True)),
                ('attempts_count', models.IntegerField(default=0, verbose_name='Попыток сделано')),
                ('last_attempt_result', models.TextField(blank=True, verbose_name='Результат последней проверки')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('xp_earned', models.IntegerField(default=0, verbose_name='Получено XP')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс',
                'verbose_name_plural': 'Прогресс пользователей',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
